<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-26 21:25
=======
# Generated by Django 4.2.3 on 2023-08-21 22:14
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
# Generated by Django 4.2.3 on 2023-08-21 22:14
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TahunAjaranModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tahun_ajaran', models.CharField(max_length=100)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('ajaran_semester', models.CharField(choices=[('Genap', 'Genap'), ('Ganjil', 'Ganjil')], max_length=100)),
=======
                ('ajaran_semester', models.CharField(choices=[('Genap', 'Genap'), ('Ganjil', 'Ganjil')], default='Ganjil', max_length=100)),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
                ('ajaran_semester', models.CharField(choices=[('Genap', 'Genap'), ('Ganjil', 'Ganjil')], default='Ganjil', max_length=100)),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
