# Generated by Django 4.2.3 on 2023-09-01 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dosen_pengajar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahasiswa', models.CharField(blank=True, max_length=100)),
                ('mata_kuliah', models.CharField(blank=True, max_length=100)),
                ('kehadiran', models.CharField(default='Tidak Hadir', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen_pengajar.dosenpengajarmodel')),
            ],
        ),
    ]
