# Generated by Django 4.2.3 on 2023-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_matkul', models.CharField()),
                ('nama_dosen', models.CharField(max_length=100)),
            ],
        ),
    ]
