# Generated by Django 4.2.3 on 2023-08-29 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0001_initial'),
        ('mahasiswa', '0001_initial'),
        ('absen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kehadiran', models.CharField(default='Tidak Hadir', max_length=20)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dosen_pengajar.dosenpengajarmodel')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa')),
            ],
        ),
        migrations.DeleteModel(
            name='AbsenModel',
        ),
    ]
