# Generated by Django 4.2.3 on 2023-08-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0002_absen_delete_absenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='absen',
            name='nama_mata_kuliah',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
