# Generated by Django 4.2.3 on 2023-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0004_rename_nama_mata_kuliah_absen_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='mahasiswa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
