<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-26 21:25
=======
# Generated by Django 4.2.3 on 2023-08-21 23:38
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
# Generated by Django 4.2.3 on 2023-08-21 23:38
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutiModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('nama', models.CharField(blank=True, max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('lama_cuti', models.CharField(max_length=100)),
                ('syarat_cuti', models.FileField(upload_to='uploads/cuti/')),
                ('keterangan', models.CharField(max_length=100)),
                ('status_cuti', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pending', max_length=100)),
=======
=======
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
                ('nama', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateTimeField()),
                ('lama_cuti', models.CharField(max_length=100)),
                ('syarat_cuti', models.FileField(upload_to='uploads/cuti/')),
                ('keterangan', models.CharField(max_length=100)),
                ('status_cuti', models.CharField(choices=[('Status', 'Status'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Status', max_length=100)),
<<<<<<< HEAD
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
            ],
        ),
    ]
