# Generated by Django 4.2.3 on 2023-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CutiModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateTimeField()),
                ('lama_cuti', models.CharField(max_length=100)),
                ('syarat_cuti', models.FileField(upload_to='uploads/cuti/')),
                ('keterangan', models.CharField(max_length=100)),
                ('status_cuti', models.CharField(choices=[('Status', 'Status'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Status', max_length=100)),
            ],
        ),
    ]
