# Generated by Django 4.2.3 on 2023-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0002_alter_cutimodel_status_cuti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutimodel',
            name='nama',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
