# Generated by Django 4.2.3 on 2023-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0003_alter_cutimodel_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutimodel',
            name='status_cuti',
            field=models.CharField(blank=True, choices=[('Status', 'Status'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Status', max_length=100),
        ),
    ]
