<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-23 19:44
=======
# Generated by Django 4.2.3 on 2023-08-22 11:45
>>>>>>> 684fe95e50371f6032566c10fbeb4e23f69f69e8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuti', '0003_alter_cutimodel_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutimodel',
            name='status_cuti',
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Pending', max_length=100),
=======
            field=models.CharField(blank=True, choices=[('Status', 'Status'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Status', max_length=100),
>>>>>>> 684fe95e50371f6032566c10fbeb4e23f69f69e8
        ),
    ]
