# Generated by Django 4.2.3 on 2023-07-22 09:34

from django.db import migrations

def create_dummy_matakuliah(apps, schema_editor):
    MataKuliah = apps.get_model('matakuliah', 'MataKuliah')

    data_dummy = [
        {'kode_mata_kuliah': 'MK001', 'nama_mata_kuliah': 'Matematika', 'jumlah_sks': 3, 'program_studi': 'Teknik Informatika', 'kelas': 'A', 'nama_pengajar': 'Dr. Ahmad'},
        {'kode_mata_kuliah': 'MK002', 'nama_mata_kuliah': 'Fisika', 'jumlah_sks': 4, 'program_studi': 'Fisika', 'kelas': 'B', 'nama_pengajar': 'Prof. Budi'},
        # Tambahkan data dummy lainnya sesuai kebutuhan
    ]

    for data in data_dummy:
        MataKuliah.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_matakuliah),
    ]
