# Generated by Django 4.2.3 on 2023-08-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Matematika Teknik', 'Matematika Teknik'), ('Struktur Data', 'Struktur Data'), ('Desain Web', 'Desain Web'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Sistem Informasi', 'Sistem Informasi')], max_length=100),
        ),
    ]
