# Generated by Django 4.2.3 on 2023-08-02 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0003_dosenpengajarmodel_kelas'),
        ('matakuliah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_pengajar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_kuliah_list', to='dosen_pengajar.dosenpengajarmodel'),
        ),
    ]
