# Generated by Django 4.2.3 on 2023-08-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Struktur Data', 'Struktur Data'), ('Sistem Informasi', 'Sistem Informasi'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Matematika Teknik', 'Matematika Teknik'), ('Desain Web', 'Desain Web')], max_length=100),
        ),
    ]
