# Generated by Django 4.2.3 on 2023-08-01 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0002_alter_dosenpengajarmodel_jk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_pengajar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matakuliah_list', to='dosen_pengajar.dosenpengajarmodel'),
        ),
    ]
