# Generated by Django 4.2.3 on 2023-08-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0002_alter_matakuliah_nama_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Sistem Informasi', 'Sistem Informasi'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Struktur Data', 'Struktur Data'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Matematika Teknik', 'Matematika Teknik'), ('Desain Web', 'Desain Web')], max_length=100),
        ),
    ]
