# Generated by Django 4.2.3 on 2023-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0003_alter_matakuliah_nama_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Sistem Informasi', 'Sistem Informasi'), ('Matematika Teknik', 'Matematika Teknik'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Desain Web', 'Desain Web'), ('Struktur Data', 'Struktur Data'), ('Algoritma Pemrograman', 'Algoritma Pemrograman')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='tipe',
            field=models.CharField(blank=True, choices=[('Praktikum', 'Praktikum'), ('Teori', 'Teori')], default='', max_length=100),
        ),
    ]
