# Generated by Django 4.2.3 on 2023-09-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0003_alter_matakuliah_nama_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Matematika Teknik', 'Matematika Teknik'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Desain Web', 'Desain Web'), ('Struktur Data', 'Struktur Data'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Sistem Informasi', 'Sistem Informasi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='tipe',
            field=models.CharField(blank=True, choices=[('Teori', 'Teori'), ('Praktikum', 'Praktikum')], default='', max_length=100),
        ),
    ]
