# Generated by Django 4.2.3 on 2023-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0004_alter_matakuliah_nama_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Desain Web', 'Desain Web'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Struktur Data', 'Struktur Data'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Matematika Teknik', 'Matematika Teknik'), ('Sistem Informasi', 'Sistem Informasi')], max_length=100),
        ),
    ]
