# Generated by Django 4.2.3 on 2023-08-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0005_alter_matakuliah_nama_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Matematika Teknik', 'Matematika Teknik'), ('Sistem Informasi', 'Sistem Informasi'), ('Struktur Data', 'Struktur Data'), ('Desain Web', 'Desain Web'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer')], max_length=100),
        ),
    ]
