# Generated by Django 4.2.3 on 2023-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0005_alter_matakuliah_nama_mata_kuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='kuota',
            field=models.IntegerField(blank=True, default=30),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='tipe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='kelas',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Struktur Data', 'Struktur Data'), ('Desain Web', 'Desain Web'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Sistem Informasi', 'Sistem Informasi'), ('Matematika Teknik', 'Matematika Teknik'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer')], max_length=100),
        ),
    ]
