# Generated by Django 4.2.3 on 2023-08-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0007_alter_matakuliah_nama_mata_kuliah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Sistem Informasi', 'Sistem Informasi'), ('Desain Web', 'Desain Web'), ('Struktur Data', 'Struktur Data'), ('Matematika Teknik', 'Matematika Teknik')], max_length=100),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='tipe',
            field=models.CharField(blank=True, choices=[('Praktikum', 'Praktikum'), ('Teori', 'Teori')], default='', max_length=100),
        ),
    ]
