# Generated by Django 4.2.3 on 2023-08-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0015_alter_matakuliah_nama_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='nama_mata_kuliah',
            field=models.CharField(choices=[('Struktur Data', 'Struktur Data'), ('Organisasi Arsitektur Komputer', 'Organisasi Arsitektur Komputer'), ('Sistem Informasi', 'Sistem Informasi'), ('Algoritma Pemrograman', 'Algoritma Pemrograman'), ('Desain Web', 'Desain Web'), ('Matematika Teknik', 'Matematika Teknik')], max_length=100),
        ),
    ]
