<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-26 21:25
=======
# Generated by Django 4.2.3 on 2023-08-24 18:02
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
# Generated by Django 4.2.3 on 2023-08-24 18:02
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
<<<<<<< HEAD
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('C', 'C'), ('D', 'D'), ('AB', 'AB'), ('A', 'A'), ('B', 'B'), ('BC', 'BC'), ('E', 'E')], default='E', max_length=2),
=======
            field=models.CharField(blank=True, choices=[('E', 'E'), ('B', 'B'), ('D', 'D'), ('A', 'A'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC')], default='E', max_length=2),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
            field=models.CharField(blank=True, choices=[('E', 'E'), ('B', 'B'), ('D', 'D'), ('A', 'A'), ('C', 'C'), ('AB', 'AB'), ('BC', 'BC')], default='E', max_length=2),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
        ),
    ]
