# Generated by Django 4.2.3 on 2023-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='nilai',
            field=models.CharField(max_length=50),
        ),
    ]
