# Generated by Django 4.2.3 on 2023-08-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('D', 'D'), ('B', 'B'), ('E', 'E'), ('C', 'C'), ('A', 'A'), ('BC', 'BC')], default='E', max_length=2),
        ),
    ]
