# Generated by Django 4.2.3 on 2023-08-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('E', 'E'), ('C', 'C'), ('B', 'B'), ('BC', 'BC'), ('A', 'A'), ('AB', 'AB'), ('D', 'D')], default='E', max_length=2),
        ),
    ]
