<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-26 21:28
=======
# Generated by Django 4.2.3 on 2023-08-26 19:20
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
# Generated by Django 4.2.3 on 2023-08-26 19:20
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0002_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
<<<<<<< HEAD
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('C', 'C'), ('A', 'A'), ('E', 'E'), ('D', 'D'), ('BC', 'BC'), ('B', 'B'), ('AB', 'AB')], default='E', max_length=2),
=======
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('BC', 'BC'), ('B', 'B'), ('A', 'A'), ('D', 'D'), ('C', 'C'), ('E', 'E')], default='E', max_length=2),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('BC', 'BC'), ('B', 'B'), ('A', 'A'), ('D', 'D'), ('C', 'C'), ('E', 'E')], default='E', max_length=2),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
        ),
    ]
