# Generated by Django 4.2.3 on 2023-08-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0002_alter_nilai_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilai',
            name='mata_kuliah',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
