# Generated by Django 4.2.3 on 2023-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0003_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('A', 'A'), ('BC', 'BC'), ('C', 'C'), ('E', 'E'), ('D', 'D'), ('B', 'B')], default='E', max_length=2),
        ),
    ]
