<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-26 21:30
=======
# Generated by Django 4.2.3 on 2023-08-26 19:39
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
# Generated by Django 4.2.3 on 2023-08-26 19:39
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0003_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
<<<<<<< HEAD
<<<<<<< HEAD
            field=models.CharField(blank=True, choices=[('B', 'B'), ('BC', 'BC'), ('E', 'E'), ('AB', 'AB'), ('C', 'C'), ('D', 'D'), ('A', 'A')], default='E', max_length=2),
=======
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('A', 'A'), ('BC', 'BC'), ('C', 'C'), ('E', 'E'), ('D', 'D'), ('B', 'B')], default='E', max_length=2),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
=======
            field=models.CharField(blank=True, choices=[('AB', 'AB'), ('A', 'A'), ('BC', 'BC'), ('C', 'C'), ('E', 'E'), ('D', 'D'), ('B', 'B')], default='E', max_length=2),
>>>>>>> e44767ec837788c4ef383bfceb6177d8c04b4d7c
        ),
    ]
