# Generated by Django 4.2.3 on 2023-08-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0004_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('D', 'D'), ('A', 'A'), ('E', 'E')], default='E', max_length=2),
        ),
    ]
