# Generated by Django 4.2.3 on 2023-08-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0005_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('BC', 'BC'), ('AB', 'AB'), ('C', 'C'), ('A', 'A'), ('B', 'B'), ('D', 'D'), ('E', 'E')], default='E', max_length=2),
        ),
    ]
