# Generated by Django 4.2.3 on 2023-08-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0006_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('AB', 'AB'), ('BC', 'BC'), ('E', 'E'), ('A', 'A'), ('C', 'C'), ('B', 'B')], default='E', max_length=2),
        ),
    ]
