# Generated by Django 4.2.3 on 2023-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilai', '0007_alter_nilaimodel_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilaimodel',
            name='nilai',
            field=models.CharField(blank=True, choices=[('BC', 'BC'), ('B', 'B'), ('D', 'D'), ('E', 'E'), ('A', 'A'), ('C', 'C'), ('AB', 'AB')], default='E', max_length=2),
        ),
    ]
