# Generated by Django 4.2.3 on 2023-08-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosenpengajarmodel',
            name='kelas',
        ),
    ]
