# Generated by Django 4.2.3 on 2023-08-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenpengajarmodel',
            name='jk',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='Laki-Laki', max_length=20),
        ),
    ]
