# Generated by Django 4.2.3 on 2023-08-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenpengajarmodel',
            name='nrp',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
