<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-28 20:34
=======
# Generated by Django 4.2.3 on 2023-07-28 20:53
>>>>>>> b573201d19246b73a8d8ef479516d6730cf4f0ec

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenpengajarmodel',
            name='jk',
<<<<<<< HEAD
            field=models.CharField(choices=[('Laki-Laki', 'L'), ('Perempuan', 'P')], default='L', max_length=20),
=======
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=20),
>>>>>>> b573201d19246b73a8d8ef479516d6730cf4f0ec
        ),
        migrations.AlterField(
            model_name='dosenpengajarmodel',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='A', max_length=100),
        ),
    ]
