# Generated by Django 4.2.3 on 2023-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0002_alter_dosenpengajarmodel_jk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenpengajarmodel',
            name='agama',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Budha', 'Budha'), ('Konghucu', 'Konghucu')], default='Islam', max_length=50),
        ),
    ]
