# Generated by Django 4.2.3 on 2023-08-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosen_pengajar', '0002_alter_dosenpengajarmodel_jk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosenpengajarmodel',
            name='kelas',
            field=models.CharField(default='3TI A', max_length=100),
        ),
    ]
