<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-16 03:55
=======
# Generated by Django 4.2.3 on 2023-08-21 11:30
>>>>>>> 45e0d6cbc057d977bbba61f29374edefff3ee7ea

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angkatan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_angkatan', models.CharField(max_length=100)),
                ('kurikulum', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
