# Generated by Django 4.2.3 on 2023-08-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angkatan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkatan',
            name='nama_angkatan',
            field=models.IntegerField(max_length=4),
        ),
    ]
