# Generated by Django 4.2.3 on 2023-08-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angkatan', '0002_alter_angkatan_nama_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angkatan',
            name='nama_angkatan',
            field=models.IntegerField(),
        ),
    ]
