# Generated by Django 4.2.3 on 2023-08-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WisudahYudisiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lulus_sidang', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('epdamo', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_prodi', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_keungan', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_bidkerjasama', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_perpus', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('toefle', models.ImageField(default='default.png', upload_to='uploads/profile/')),
            ],
        ),
    ]
