# Generated by Django 4.2.3 on 2023-08-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisudah_yudisium', '0002_rename_lulus_keungan_wisudahyudisiummodel_lulus_keunganan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wisudahyudisiummodel',
            old_name='lulus_keunganan',
            new_name='lulus_keungan',
        ),
    ]
