# Generated by Django 4.2.3 on 2023-08-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_alter_mahasiswa_agama'),
        ('wisudah_yudisium', '0007_alter_wisudahyudisiummodel_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisudahyudisiummodel',
            name='nama',
        ),
        migrations.AddField(
            model_name='wisudahyudisiummodel',
            name='nim',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa'),
        ),
    ]
