# Generated by Django 4.2.3 on 2023-08-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs',
            name='nilai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
