# Generated by Django 4.2.3 on 2023-08-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='krs',
            name='status',
            field=models.CharField(default='belum di acc', max_length=20),
        ),
    ]
