# Generated by Django 4.2.3 on 2023-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0002_matakuliah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matakuliah',
            name='sks',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='jumlah_sks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='krs',
            name='status',
            field=models.CharField(default='belum disetujui', max_length=20),
        ),
    ]
