# Generated by Django 4.2.3 on 2023-08-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0002_krs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs',
            name='mahasiswa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='krs',
            name='mata_kuliah',
            field=models.CharField(max_length=100),
        ),
    ]
