# Generated by Django 4.2.3 on 2023-08-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matakuliah', '0005_alter_matakuliah_nama_mata_kuliah'),
        ('krs', '0003_remove_matakuliah_sks_matakuliah_jumlah_sks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matakuliah.matakuliah'),
        ),
    ]
