# Generated by Django 4.2.3 on 2023-08-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0004_alter_krs_mata_kuliah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs',
            name='mata_kuliah',
            field=models.CharField(max_length=200),
        ),
    ]
