# Generated by Django 4.2.3 on 2023-08-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0005_alter_krs_mata_kuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('angkatan', models.CharField(max_length=4)),
                ('jurusan', models.CharField(max_length=100)),
            ],
        ),
    ]
