# Generated by Django 4.2.3 on 2023-08-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0007_delete_mahasiswa_alter_krs_mahasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='krs',
            name='nilai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
