# Generated by Django 4.2.3 on 2023-08-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WisudahYudisiumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lulus_sidang', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('epdamo', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_prodi', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_keuangan', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_bidkerjasama', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('lulus_perpus', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('toefl', models.ImageField(default='default.png', upload_to='uploads/profile/')),
                ('nim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa')),
            ],
        ),
    ]
