# Generated by Django 4.2.3 on 2023-08-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisudah_yudisium', '0003_rename_lulus_keunganan_wisudahyudisiummodel_lulus_keungan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wisudahyudisiummodel',
            old_name='lulus_keungan',
            new_name='lulus_keuangan',
        ),
    ]
