# Generated by Django 4.2.3 on 2023-08-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisudah_yudisium', '0004_rename_lulus_keungan_wisudahyudisiummodel_lulus_keuangan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wisudahyudisiummodel',
            old_name='toefle',
            new_name='toefl',
        ),
    ]
