# Generated by Django 4.2.3 on 2023-08-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_alter_mahasiswa_agama'),
        ('wisudah_yudisium', '0006_wisudahyudisiummodel_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisudahyudisiummodel',
            name='nama',
            field=models.OneToOneField(default='nim', on_delete=django.db.models.deletion.CASCADE, to='mahasiswa.mahasiswa'),
        ),
    ]
