# Generated by Django 4.2.3 on 2023-07-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nim', models.IntegerField(primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=1000, null=True)),
                ('nama', models.CharField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('angkatan', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('jk', models.CharField(max_length=1)),
                ('agama', models.CharField(max_length=20)),
                ('beasiswa', models.CharField(max_length=20)),
            ],
        ),
    ]
