# Generated by Django 4.2.3 on 2023-08-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='doswal',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
