# Generated by Django 4.2.3 on 2023-07-22 21:19

from django.db import migrations


def create_dummy_mahasiswa(apps, schema_editor):
    Mahasiswa = apps.get_model('mahasiswa', 'Mahasiswa')

    data_dummy = [
        {'nim': '1010101010', 'foto': '', 'nama': 'memed', 'tempat_lahir': 'Banda Aceh', 'tanggal_lahir': '2000-12-12',
            'angkatan': 2020, 'semester': 6, 'jk': 'L', 'agama': 'Islam', 'beasiswa': 'KIP'},
        {'nim': '2020202020', 'foto': '', 'nama': 'Muna', 'tempat_lahir': 'Aceh Besar', 'tanggal_lahir': '2001-2-23',
            'angkatan': 2020, 'semester': 6, 'jk': 'P', 'agama': 'Islam', 'beasiswa': 'KIP'},
        # Tambahkan data dummy lainnya sesuai kebutuhan
    ]

    for data in data_dummy:
        Mahasiswa.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_mahasiswa),
    ]
