# Generated by Django 4.2.3 on 2023-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_mahasiswa_doswal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Tidak Aktif', 'Tidak Aktif')], default='A', max_length=100),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='jk',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], default='L', max_length=20),
        ),
    ]
